[project]
name = "aiogram3-template"
version = "0.1.0"
description = "Template for creating a Telegram bot"
authors = [
    {name = "Shardyllue",email = "shardyllye@gmail.com"}
]
license = {text = "GNU"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram (>=3.18.0,<4.0.0)",
    "pydantic-settings (>=2.8.1,<3.0.0)",
    "aiogram-i18n[runtime] (>=1.4,<2.0)",
    "libcst (>=1.6.0,<2.0.0)",
    "sqlalchemy (>=2.0.38,<3.0.0)",
    "alembic (>=1.14.1,<2.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
<<<<<<< HEAD
    "psycopg2-binary (>=2.9.10,<3.0.0)"
=======
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "redis (>=5.2.1,<6.0.0)"
>>>>>>> 01a728c (update: DDD)
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
mypy = "^1.15.0"

