services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
<<<<<<< HEAD

volumes:
  database_data:
=======
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: 
      - --requirepass $REDIS_PASSWORD
    

volumes:
  database_data:
  redis_data:
>>>>>>> 01a728c (update: DDD)
    