services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
<<<<<<< HEAD
=======
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
>>>>>>> 01a728c (update: DDD)
  bot:
    build:
      context: ..
      dockerfile: app/Dockerfile
    container_name: bot
    command: "python run.py"
    env_file:
      - ../.env
    depends_on:
      - postgres
<<<<<<< HEAD

volumes:
  database_data:
=======
      - redis

volumes:
  database_data:
  redis_data:
>>>>>>> 01a728c (update: DDD)
    